### ISSUE TITLE
about SauceNAO Telegrambot cannot be used with Telegram

### ISSUE THREAD

**Issue by Root-1404** [Eptagone/SauceNAObot#1]
![捕获](https://user-images.githubusercontent.com/77722478/134911138-54b379c9-7e0a-47ec-b79d-a82e860f528b.PNG)

**Comment by Eptagone** [comment]
The API can only perform a certain number of searches in a certain amount of time. If that limit is exceeded, the bot will send you that message.
Sometimes, the API refuses to search for a specific image for some reason. If that happens, you just have to wait and after a while try searching again.
