### ISSUE TITLE
bot just stops and does nothing

### ISSUE THREAD

**Issue by Ammoswift** [Eptagone/SauceNAObot#2]
![Web capture_13-3-2022_173935_](https://user-images.githubusercontent.com/56969344/158082231-f548978f-dbd9-4b65-aca8-876b9f4adaa7.jpeg)
 Reason why it looks like this? I downloaded the chat data. Anyways....The bot just stopped working and then I tried send a few messages to the bot just doesn't respond, just stops completely. What should i do?

**Comment by Eptagone** [comment]
The server was under maintenance. It's already working.
You can check the support chat when you see that the bot does not work.
Notices about it are usually sent in the support chat: https://t.me/+8NJMCbRmiTk2Yjkx
